# Application Configuration
server:
  port: 8094

# Spring
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment-service?useUnicode=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

Feing:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"